### ISSUE TITLE
Seems broken in WU6

### ISSUE THREAD

**Issue by sonicviz** [spitice/msfs-input-viewer#1]
No response to control inputs anymore

**Comment by spitice** [comment]
Thanks for your report!

That's strange because, on my side, the addon works without any issues even after WU6 as well as today's hotfix.

If the root cause is the addon itself, I reckon the config data for the addon might be somehow corrupted, but I'm not sure, tbh.

I'm not 100% sure about this topic either but there are many reports posted by the community that MSFS downloader sometimes does poor jobs, and game files ended up being broken. So there's a chance some of the files that the addon depending on are not working properly after the update. In those cases, the safest thing to do is to remove packages in a bad form and letting the sim download those files and hope it fixes, but it takes considerable time.

If you have MSFS SDK installed on your machine, then [you can easily check the logs in the UI debugger app](https://github.com/spitice/msfs-input-viewer/wiki/How-to-capture-logs). Posting those log data would be appreciated.

**Comment by sonicviz** [comment]
Thanks, I'll retest it. Sent from my Galaxy smartphone.
-------- Original message --------From: spitice ***@***.***> Date: 19/9/21  12:18 am  (GMT+09:00) To: spitice/msfs-input-viewer ***@***.***> Cc: Paul Cohen ***@***.***>, Author ***@***.***> Subject: Re: [spitice/msfs-input-viewer] Seems broken in WU6 (#1) 
Thanks for your report!
That's strange because, on my side, the addon works without any issues even after WU6 as well as today's hotfix.
If the root cause is the addon itself, I reckon the config data for the addon might be somehow corrupted, but I'm not sure, tbh.
I'm not 100% sure about this topic either but there are many reports posted by the community that MSFS downloader sometimes does poor jobs, and game files ended up being broken. So there's a chance some of the files that the addon depending on are not working properly after the update. In those cases, the safest thing to do is to remove packages in a bad form and letting the sim download those files and hope it fixes, but it takes considerable time.
If you have MSFS SDK installed on your machine, then you can easily check the logs in the UI debugger app. Posting those log data would be appreciated.

**Comment by sonicviz** [comment]
ah, that would be because I'm still on 1.2.0

Doh!

**Comment by sonicviz** [comment]
Hi. I wanted to have a play with the js features of the SDK, and I like what you're doing with the ts. 
Could you explain what the build process for this is? 
I see the scripts in package.json, but interested in what you typically do?

I guess installation is npm install as per usual to grab the dependancies? Edit: yes, confirmed.

Where to set $MSFS_SDK? I'm using VSCode on Win 11, but it's not picking it up as a system environment variable, which works in regular batch scripts.

Maybe add that to the readme?

Thanks!

**Comment by spitice** [comment]
Hi. I hopefully get free time tomorrow so I will try to make a more detailed guide for this topic. But, it is basically done by the following steps:

- **Prerequisites:**
  - VSCode, MSFS SDK, yarn (or another package manager like npm or pnpm)
  - `yarn init` or `npm init` (depends on your package manager) so all dependencies are ready
  - Valid InGamePanel files (.spb and icon file) must be located in the community addon directory as they cannot be updated during MSFS is running
- Open **VSCode, CoherentGT Debugger** (MSFS SDK), and **MSFS**
- VSCode: `yarn watch` or `npm run watch`
  - webpack-watch starts
  - `cpx` starts and watches `static/**/*` so static files will be copied to destination
- MSFS: Dev mode ON, open the project file (`input-viewer.xml`)
  - By doing so, MSFS will start watching the package destination (`Packages/your-addon-name`) and override the files located in the community addon directory, so you don't need to restart MSFS every time assets get updated.
- Start flight > InGamePanel will be loaded in the game
- CoherentGT Debugger: Open the InGamePanel
  - Whenever the assets used in the InGamePanel change, click reload

For `${MSFS_SDK}`, IIRC only yarn can recognize it as env variable, and npm cannot. So, maybe you need to specify the path to SDK directly or replace it with a batch file.
However, I never use `build` and `build-msfs` anymore since it consumes a very long time to load up the msfs packaging tool somehow. Instead, I typically use `build-without-msfs`, then build the package on MSFS to generate files for releasing it.

**Comment by sonicviz** [comment]
Thanks
